<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PedidoItemSeeder extends Seeder
{

    public function run()
    {
        $now = Carbon::now();

        DB::table("pedidoitem")->insert([
            [
                "codemp" => '0101',
                "pedido_id" => 1,
                "produto" => 10,
                "quant" => 2,
                "vlrunit" => 45,
                "vlrtotal" => 90,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 2,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 3,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "pedido_id" => 4,
                "produto" => 10,
                "quant" => 2,
                "vlrunit" => 45,
                "vlrtotal" => 90,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 5,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 6,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "pedido_id" => 7,
                "produto" => 10,
                "quant" => 2,
                "vlrunit" => 45,
                "vlrtotal" => 90,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 8,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 9,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "pedido_id" => 10,
                "produto" => 10,
                "quant" => 2,
                "vlrunit" => 45,
                "vlrtotal" => 90,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 1,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 11,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "pedido_id" => 12,
                "produto" => 10,
                "quant" => 2,
                "vlrunit" => 45,
                "vlrtotal" => 90,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 13,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 14,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "pedido_id" => 15,
                "produto" => 10,
                "quant" => 2,
                "vlrunit" => 45,
                "vlrtotal" => 90,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 16,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 17,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "pedido_id" => 18,
                "produto" => 10,
                "quant" => 2,
                "vlrunit" => 45,
                "vlrtotal" => 90,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 19,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 20,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "pedido_id" => 21,
                "produto" => 10,
                "quant" => 2,
                "vlrunit" => 45,
                "vlrtotal" => 90,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 22,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 23,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 24,
                "produto" => 11,
                "quant" => 1,
                "vlrunit" => 20,
                "vlrtotal" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "codemp" => '0101',
                "pedido_id" => 25,
                "produto" => 10,
                "quant" => 1,
                "vlrunit" => 1,
                "vlrtotal" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],

        ]);

    }

}
