<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PedidoSeeder extends Seeder
{

    public function run()
    {

        $now = Carbon::now();
        $now_dia_ontem1 = Carbon::now()->subDays(1);
        $now_dia_ontem2 = Carbon::now()->subDays(2);
        $now_dia_ontem3 = Carbon::now()->subDays(3);
        $now_dia_ontem4 = Carbon::now()->subDays(4);
        $now_dia_ontem5 = Carbon::now()->subDays(5);
        $now_dia_ontem6 = Carbon::now()->subDays(6);
        $now_dia_ontem8 = Carbon::now()->subDays(8);
        $now_dia_ontem15 = Carbon::now()->subDays(15);
        $now_dia_ontem16 = Carbon::now()->subDays(16);
        $now_dia_ontem17 = Carbon::now()->subDays(17);
        $now_dia_ontem18 = Carbon::now()->subDays(18);

        $now_mes_mais_um = Carbon::now()->addMonths(1);
        $now_mes_mais_dois = Carbon::now()->addMonths(2);
        $now_mes_mais_tres = Carbon::now()->addMonths(3);


        DB::table("pedido")->insert([

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000001",
                "cliente" => '0013',
                "condpgto" => '03',
                "formapgto" => 1,
                "dtemissao" => $now_dia_ontem15,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "C",
                "valor" => 7500,
                "peso" => 710,
                "created_at" => $now_dia_ontem15,
                "updated_at" => $now_dia_ontem15,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000002",
                "cliente" => '0013',
                "condpgto" => '01',
                "formapgto" => 1,
                "dtemissao" => $now_dia_ontem16,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "C",
                "valor" => 5200,
                "peso" => 210,
                "created_at" => $now_dia_ontem16,
                "updated_at" => $now_dia_ontem16,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000003",
                "cliente" => '0013',
                "condpgto" => '01',
                "formapgto" => 1,
                "dtemissao" => $now_dia_ontem17,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "C",
                "valor" => 200,
                "peso" => 20,
                "created_at" => $now_dia_ontem17,
                "updated_at" => $now_dia_ontem17,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000503",
                "cliente" => '0013',
                "condpgto" => '01',
                "formapgto" => 1,
                "dtemissao" => $now_dia_ontem18,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "C",
                "valor" => 400,
                "peso" => 50,
                "created_at" => $now_dia_ontem18,
                "updated_at" => $now_dia_ontem18,
            ],


            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000004",
                "cliente" => '0013',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_dia_ontem8,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "C",
                "valor" => 8000,
                "peso" => 800,
                "created_at" => $now_dia_ontem8,
                "updated_at" => $now_dia_ontem8,
            ],


            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000005",
                "cliente" => '0013',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_dia_ontem6,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "C",
                "valor" => 2000,
                "peso" => 400,
                "created_at" => $now_dia_ontem6,
                "updated_at" => $now_dia_ontem6,
            ],


            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000006",
                "cliente" => '0013',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_dia_ontem6,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "C",
                "valor" => 4000,
                "peso" => 200,
                "created_at" => $now_dia_ontem6,
                "updated_at" => $now_dia_ontem6,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000097",
                "cliente" => '0013',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_dia_ontem6,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 110,
                "peso" => 10,
                "created_at" => $now_dia_ontem6,
                "updated_at" => $now_dia_ontem6,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000007",
                "cliente" => '0013',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_um,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 1110,
                "peso" => 100,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000009",
                "cliente" => '0016',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 200,
                "peso" => 20,
                "created_at" => $now_mes_mais_um,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000010",
                "cliente" => '0016',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now,
                "dtfatura" => $now_mes_mais_dois,
                "numfatura" => '00887',
                "status" => "F",
                "valor" => 100,
                "peso" => 10,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000011",
                "cliente" => '0016',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now,
                "dtfatura" => $now_mes_mais_dois,
                "numfatura" => '00887',
                "status" => "F",
                "valor" => 5500,
                "peso" => 550,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000012",
                "cliente" => '0016',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now,
                "dtfatura" => $now_mes_mais_dois,
                "numfatura" => '00887',
                "status" => "F",
                "valor" => 7400,
                "peso" => 580,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000013",
                "cliente" => '0022',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now,
                "dtfatura" => $now_mes_mais_dois,
                "numfatura" => '00887',
                "status" => "F",
                "valor" => 400,
                "peso" => 20,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000014",
                "cliente" => '0013',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now,
                "dtfatura" => $now_mes_mais_dois,
                "numfatura" => '00887',
                "status" => "F",
                "valor" => 110,
                "peso" => 10,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000015",
                "cliente" => '0022',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 150,
                "peso" => 8,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000016",
                "cliente" => '0022',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 160,
                "peso" => 22,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000017",
                "cliente" => '0013',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 55.4,
                "peso" => 1,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000018",
                "cliente" => '0022',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 88.9,
                "peso" => 10,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000019",
                "cliente" => '0031',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 99.9,
                "peso" => 400,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000020",
                "cliente" => '0031',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 99.9,
                "peso" => 200,
                "created_at" => $now,
                "updated_at" => $now,
            ],


            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000021",
                "cliente" => '0031',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 9999.9,
                "peso" => 400,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000022",
                "cliente" => '0031',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 4000,
                "peso" => 400,
                "created_at" => $now,
                "updated_at" => $now,
            ],

            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000023",
                "cliente" => '0031',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 2230,
                "peso" => 210,
                "created_at" => $now,
                "updated_at" => $now,
            ],



            [
                "codemp" => '0101',
                "loja" => "01",
                "tipo" => "P",
                "codigo" => "000024",
                "cliente" => '0031',
                "condpgto" => '02',
                "formapgto" => 1,
                "dtemissao" => $now_mes_mais_tres,
                "dtfatura" => '1990-01-01',
                "numfatura" => '',
                "status" => "A",
                "valor" => 2231,
                "peso" => 400,
                "created_at" => $now,
                "updated_at" => $now,
            ],

        ]);

    }

}
